### ISSUE TITLE
Blips

### ISSUE THREAD

**Issue by JLDLR** [CookiePLMonster/ExGangWars#4]
Hello. It seems the mod doesn't work well with the HD User Interface mod. Or so I think. The blips are not displaying correctly, I get the red flag for the Aztecas. If you can tell me the blip codes I can fix it on my end I think. Thanks Cook.

**Comment by CookiePLMonster** [comment]
If I remember correctly, blip sprite IDs were included in the mod's INI file, you can also check them on the GTA Mods Wiki:
https://gtamods.com/wiki/Blip#San_Andreas

**Comment by JLDLR** [comment]
Yeah, I checked, everything ~should~ be fine, but there's something weird. But I think I know the cause (leftover gangzones from the bikers and russians mod, I tried it and didn't like it, but the gangzones stay with the savegame). Thanks!
